spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/blps?currentSchema=lab4
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

camunda.bpm.admin-user:
  id: demo
  password: demo
server:
  port: 8082