spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/camunda?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
     # ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

camunda:
  bpm:
    admin-user:
      password: demo
      id: demo

server:
  port: 8080